### ISSUE TITLE
Adicionar readme da página wiki

### ISSUE THREAD

**Issue by alinebrito** [cefetmg-2022-psi-g005/wiki#13]
Olá pessoal!

Sugestões para a entrega final (23/11): 

Adicionar o arquivo ``README`` da página wiki, com o link para a documentação e descrição geral do sistema.

Sugiro também que finalizem as issues abertas que já foram concluídas.

**Comment by evelynlaura** [comment]
https://github.com/cefetmg-2022-psi-g005/wiki#plataforma-matchmaking
